/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Link;
import com.konfigthis.client.model.PayComponentResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CheckResource
 */
public class CheckResourceTest {
    private final CheckResource model = new CheckResource();

    /**
     * Model tests for CheckResource
     */
    @Test
    public void testCheckResource() {
        // TODO: test CheckResource
    }

    /**
     * Test the property 'workerId'
     */
    @Test
    public void workerIdTest() {
        // TODO: test workerId
    }

    /**
     * Test the property 'paycheckId'
     */
    @Test
    public void paycheckIdTest() {
        // TODO: test paycheckId
    }

    /**
     * Test the property 'payPeriodId'
     */
    @Test
    public void payPeriodIdTest() {
        // TODO: test payPeriodId
    }

    /**
     * Test the property 'checkCorrelationId'
     */
    @Test
    public void checkCorrelationIdTest() {
        // TODO: test checkCorrelationId
    }

    /**
     * Test the property 'blockAutoDistribution'
     */
    @Test
    public void blockAutoDistributionTest() {
        // TODO: test blockAutoDistribution
    }

    /**
     * Test the property 'earnings'
     */
    @Test
    public void earningsTest() {
        // TODO: test earnings
    }

    /**
     * Test the property 'deductions'
     */
    @Test
    public void deductionsTest() {
        // TODO: test deductions
    }

    /**
     * Test the property 'checkDate'
     */
    @Test
    public void checkDateTest() {
        // TODO: test checkDate
    }

    /**
     * Test the property 'informational'
     */
    @Test
    public void informationalTest() {
        // TODO: test informational
    }

    /**
     * Test the property 'taxes'
     */
    @Test
    public void taxesTest() {
        // TODO: test taxes
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
