/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ClientAccountRegistration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ClientAccount
 */
public class ClientAccountTest {
    private final ClientAccount model = new ClientAccount();

    /**
     * Model tests for ClientAccount
     */
    @Test
    public void testClientAccount() {
        // TODO: test ClientAccount
    }

    /**
     * Test the property 'externalCAID'
     */
    @Test
    public void externalCAIDTest() {
        // TODO: test externalCAID
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'lockVersion'
     */
    @Test
    public void lockVersionTest() {
        // TODO: test lockVersion
    }

    /**
     * Test the property 'applicationName'
     */
    @Test
    public void applicationNameTest() {
        // TODO: test applicationName
    }

    /**
     * Test the property 'assignedName'
     */
    @Test
    public void assignedNameTest() {
        // TODO: test assignedName
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'createdByApplicationName'
     */
    @Test
    public void createdByApplicationNameTest() {
        // TODO: test createdByApplicationName
    }

    /**
     * Test the property 'createdByUserId'
     */
    @Test
    public void createdByUserIdTest() {
        // TODO: test createdByUserId
    }

    /**
     * Test the property 'routeAttributeName'
     */
    @Test
    public void routeAttributeNameTest() {
        // TODO: test routeAttributeName
    }

    /**
     * Test the property 'createdByApplicationSubProcessName'
     */
    @Test
    public void createdByApplicationSubProcessNameTest() {
        // TODO: test createdByApplicationSubProcessName
    }

    /**
     * Test the property 'routeAttributeValue'
     */
    @Test
    public void routeAttributeValueTest() {
        // TODO: test routeAttributeValue
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'modifiedByApplicationName'
     */
    @Test
    public void modifiedByApplicationNameTest() {
        // TODO: test modifiedByApplicationName
    }

    /**
     * Test the property 'modifiedByApplicationSubProcessName'
     */
    @Test
    public void modifiedByApplicationSubProcessNameTest() {
        // TODO: test modifiedByApplicationSubProcessName
    }

    /**
     * Test the property 'modifiedByUserId'
     */
    @Test
    public void modifiedByUserIdTest() {
        // TODO: test modifiedByUserId
    }

    /**
     * Test the property 'parentIndicator'
     */
    @Test
    public void parentIndicatorTest() {
        // TODO: test parentIndicator
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'clientAccountRegistrations'
     */
    @Test
    public void clientAccountRegistrationsTest() {
        // TODO: test clientAccountRegistrations
    }

    /**
     * Test the property 'caid'
     */
    @Test
    public void caidTest() {
        // TODO: test caid
    }

}
