/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Client;
import com.konfigthis.client.model.ClientAccount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ClientAccountRegistration
 */
public class ClientAccountRegistrationTest {
    private final ClientAccountRegistration model = new ClientAccountRegistration();

    /**
     * Model tests for ClientAccountRegistration
     */
    @Test
    public void testClientAccountRegistration() {
        // TODO: test ClientAccountRegistration
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'endReasonCode'
     */
    @Test
    public void endReasonCodeTest() {
        // TODO: test endReasonCode
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'createdByApplicationName'
     */
    @Test
    public void createdByApplicationNameTest() {
        // TODO: test createdByApplicationName
    }

    /**
     * Test the property 'createdByUserId'
     */
    @Test
    public void createdByUserIdTest() {
        // TODO: test createdByUserId
    }

    /**
     * Test the property 'createdByApplicationSubProcessName'
     */
    @Test
    public void createdByApplicationSubProcessNameTest() {
        // TODO: test createdByApplicationSubProcessName
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'modifiedByApplicationName'
     */
    @Test
    public void modifiedByApplicationNameTest() {
        // TODO: test modifiedByApplicationName
    }

    /**
     * Test the property 'modifiedByApplicationSubProcessName'
     */
    @Test
    public void modifiedByApplicationSubProcessNameTest() {
        // TODO: test modifiedByApplicationSubProcessName
    }

    /**
     * Test the property 'modifiedByUserId'
     */
    @Test
    public void modifiedByUserIdTest() {
        // TODO: test modifiedByUserId
    }

    /**
     * Test the property 'client'
     */
    @Test
    public void clientTest() {
        // TODO: test client
    }

    /**
     * Test the property 'clientAccount'
     */
    @Test
    public void clientAccountTest() {
        // TODO: test clientAccount
    }

}
