/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ClientName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ClientNameVersion
 */
public class ClientNameVersionTest {
    private final ClientNameVersion model = new ClientNameVersion();

    /**
     * Model tests for ClientNameVersion
     */
    @Test
    public void testClientNameVersion() {
        // TODO: test ClientNameVersion
    }

    /**
     * Test the property 'cnvId'
     */
    @Test
    public void cnvIdTest() {
        // TODO: test cnvId
    }

    /**
     * Test the property 'cnvCltNm'
     */
    @Test
    public void cnvCltNmTest() {
        // TODO: test cnvCltNm
    }

    /**
     * Test the property 'cnvVerStatCd'
     */
    @Test
    public void cnvVerStatCdTest() {
        // TODO: test cnvVerStatCd
    }

    /**
     * Test the property 'cnvValStatCd'
     */
    @Test
    public void cnvValStatCdTest() {
        // TODO: test cnvValStatCd
    }

    /**
     * Test the property 'cnvBegnEffDt'
     */
    @Test
    public void cnvBegnEffDtTest() {
        // TODO: test cnvBegnEffDt
    }

    /**
     * Test the property 'cnvEndEffDt'
     */
    @Test
    public void cnvEndEffDtTest() {
        // TODO: test cnvEndEffDt
    }

    /**
     * Test the property 'cnvModDt'
     */
    @Test
    public void cnvModDtTest() {
        // TODO: test cnvModDt
    }

    /**
     * Test the property 'cnvModByAppNm'
     */
    @Test
    public void cnvModByAppNmTest() {
        // TODO: test cnvModByAppNm
    }

    /**
     * Test the property 'cnvModByAppUsrNm'
     */
    @Test
    public void cnvModByAppUsrNmTest() {
        // TODO: test cnvModByAppUsrNm
    }

    /**
     * Test the property 'cnvModByAppSubNm'
     */
    @Test
    public void cnvModByAppSubNmTest() {
        // TODO: test cnvModByAppSubNm
    }

    /**
     * Test the property 'cltNmByCnId'
     */
    @Test
    public void cltNmByCnIdTest() {
        // TODO: test cltNmByCnId
    }

}
