/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Link;
import com.konfigthis.client.model.PayComponentFrequencyTypeResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FrequencyCombinationUnitResource
 */
public class FrequencyCombinationUnitResourceTest {
    private final FrequencyCombinationUnitResource model = new FrequencyCombinationUnitResource();

    /**
     * Model tests for FrequencyCombinationUnitResource
     */
    @Test
    public void testFrequencyCombinationUnitResource() {
        // TODO: test FrequencyCombinationUnitResource
    }

    /**
     * Test the property 'payFrequency'
     */
    @Test
    public void payFrequencyTest() {
        // TODO: test payFrequency
    }

    /**
     * Test the property 'payComponentFrequency'
     */
    @Test
    public void payComponentFrequencyTest() {
        // TODO: test payComponentFrequency
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
