/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EmailResource;
import com.konfigthis.client.model.PostalResource;
import com.konfigthis.client.model.TelecomResource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonCommunicationResource
 */
public class PersonCommunicationResourceTest {
    private final PersonCommunicationResource model = new PersonCommunicationResource();

    /**
     * Model tests for PersonCommunicationResource
     */
    @Test
    public void testPersonCommunicationResource() {
        // TODO: test PersonCommunicationResource
    }

    /**
     * Test the property 'telecom'
     */
    @Test
    public void telecomTest() {
        // TODO: test telecom
    }

    /**
     * Test the property 'postal'
     */
    @Test
    public void postalTest() {
        // TODO: test postal
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

}
