/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PostalResource
 */
public class PostalResourceTest {
    private final PostalResource model = new PostalResource();

    /**
     * Model tests for PostalResource
     */
    @Test
    public void testPostalResource() {
        // TODO: test PostalResource
    }

    /**
     * Test the property 'communicationId'
     */
    @Test
    public void communicationIdTest() {
        // TODO: test communicationId
    }

    /**
     * Test the property 'streetLineOne'
     */
    @Test
    public void streetLineOneTest() {
        // TODO: test streetLineOne
    }

    /**
     * Test the property 'streetLineTwo'
     */
    @Test
    public void streetLineTwoTest() {
        // TODO: test streetLineTwo
    }

    /**
     * Test the property 'postOfficeBox'
     */
    @Test
    public void postOfficeBoxTest() {
        // TODO: test postOfficeBox
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'countrySubdivisionCode'
     */
    @Test
    public void countrySubdivisionCodeTest() {
        // TODO: test countrySubdivisionCode
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

}
