/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Link;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkerStatus
 */
public class WorkerStatusTest {
    private final WorkerStatus model = new WorkerStatus();

    /**
     * Model tests for WorkerStatus
     */
    @Test
    public void testWorkerStatus() {
        // TODO: test WorkerStatus
    }

    /**
     * Test the property 'workerStatusId'
     */
    @Test
    public void workerStatusIdTest() {
        // TODO: test workerStatusId
    }

    /**
     * Test the property 'statusType'
     */
    @Test
    public void statusTypeTest() {
        // TODO: test statusType
    }

    /**
     * Test the property 'statusReason'
     */
    @Test
    public void statusReasonTest() {
        // TODO: test statusReason
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
