/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CalcMethod;
import com.konfigthis.client.model.ClientPayComponentFrequency;
import com.konfigthis.client.model.ClientPayComponentOptions;
import com.konfigthis.client.model.ClientPayComponentWorkerTypes;
import com.konfigthis.client.model.PayComponent;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ClientPayComponentResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ClientPayComponentResponse {
  public static final String SERIALIZED_NAME_PAY_COMPONENT = "payComponent";
  @SerializedName(SERIALIZED_NAME_PAY_COMPONENT)
  private PayComponent payComponent;

  public static final String SERIALIZED_NAME_FREQUENCY_DATA = "frequencyData";
  @SerializedName(SERIALIZED_NAME_FREQUENCY_DATA)
  private ClientPayComponentFrequency frequencyData;

  public static final String SERIALIZED_NAME_CALC_METHODS = "calcMethods";
  @SerializedName(SERIALIZED_NAME_CALC_METHODS)
  private List<CalcMethod> calcMethods = null;

  public static final String SERIALIZED_NAME_WORKER_TYPES = "workerTypes";
  @SerializedName(SERIALIZED_NAME_WORKER_TYPES)
  private List<ClientPayComponentWorkerTypes> workerTypes = null;

  public static final String SERIALIZED_NAME_OPTIONS = "options";
  @SerializedName(SERIALIZED_NAME_OPTIONS)
  private List<ClientPayComponentOptions> options = null;

  public ClientPayComponentResponse() {
  }

  public ClientPayComponentResponse payComponent(PayComponent payComponent) {
    
    
    
    
    this.payComponent = payComponent;
    return this;
  }

   /**
   * Get payComponent
   * @return payComponent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PayComponent getPayComponent() {
    return payComponent;
  }


  public void setPayComponent(PayComponent payComponent) {
    
    
    
    this.payComponent = payComponent;
  }


  public ClientPayComponentResponse frequencyData(ClientPayComponentFrequency frequencyData) {
    
    
    
    
    this.frequencyData = frequencyData;
    return this;
  }

   /**
   * Get frequencyData
   * @return frequencyData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClientPayComponentFrequency getFrequencyData() {
    return frequencyData;
  }


  public void setFrequencyData(ClientPayComponentFrequency frequencyData) {
    
    
    
    this.frequencyData = frequencyData;
  }


  public ClientPayComponentResponse calcMethods(List<CalcMethod> calcMethods) {
    
    
    
    
    this.calcMethods = calcMethods;
    return this;
  }

  public ClientPayComponentResponse addCalcMethodsItem(CalcMethod calcMethodsItem) {
    if (this.calcMethods == null) {
      this.calcMethods = new ArrayList<>();
    }
    this.calcMethods.add(calcMethodsItem);
    return this;
  }

   /**
   * Get calcMethods
   * @return calcMethods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CalcMethod> getCalcMethods() {
    return calcMethods;
  }


  public void setCalcMethods(List<CalcMethod> calcMethods) {
    
    
    
    this.calcMethods = calcMethods;
  }


  public ClientPayComponentResponse workerTypes(List<ClientPayComponentWorkerTypes> workerTypes) {
    
    
    
    
    this.workerTypes = workerTypes;
    return this;
  }

  public ClientPayComponentResponse addWorkerTypesItem(ClientPayComponentWorkerTypes workerTypesItem) {
    if (this.workerTypes == null) {
      this.workerTypes = new ArrayList<>();
    }
    this.workerTypes.add(workerTypesItem);
    return this;
  }

   /**
   * Get workerTypes
   * @return workerTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ClientPayComponentWorkerTypes> getWorkerTypes() {
    return workerTypes;
  }


  public void setWorkerTypes(List<ClientPayComponentWorkerTypes> workerTypes) {
    
    
    
    this.workerTypes = workerTypes;
  }


  public ClientPayComponentResponse options(List<ClientPayComponentOptions> options) {
    
    
    
    
    this.options = options;
    return this;
  }

  public ClientPayComponentResponse addOptionsItem(ClientPayComponentOptions optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<>();
    }
    this.options.add(optionsItem);
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ClientPayComponentOptions> getOptions() {
    return options;
  }


  public void setOptions(List<ClientPayComponentOptions> options) {
    
    
    
    this.options = options;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ClientPayComponentResponse instance itself
   */
  public ClientPayComponentResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientPayComponentResponse clientPayComponentResponse = (ClientPayComponentResponse) o;
    return Objects.equals(this.payComponent, clientPayComponentResponse.payComponent) &&
        Objects.equals(this.frequencyData, clientPayComponentResponse.frequencyData) &&
        Objects.equals(this.calcMethods, clientPayComponentResponse.calcMethods) &&
        Objects.equals(this.workerTypes, clientPayComponentResponse.workerTypes) &&
        Objects.equals(this.options, clientPayComponentResponse.options)&&
        Objects.equals(this.additionalProperties, clientPayComponentResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payComponent, frequencyData, calcMethods, workerTypes, options, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientPayComponentResponse {\n");
    sb.append("    payComponent: ").append(toIndentedString(payComponent)).append("\n");
    sb.append("    frequencyData: ").append(toIndentedString(frequencyData)).append("\n");
    sb.append("    calcMethods: ").append(toIndentedString(calcMethods)).append("\n");
    sb.append("    workerTypes: ").append(toIndentedString(workerTypes)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("payComponent");
    openapiFields.add("frequencyData");
    openapiFields.add("calcMethods");
    openapiFields.add("workerTypes");
    openapiFields.add("options");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ClientPayComponentResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ClientPayComponentResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ClientPayComponentResponse is not found in the empty JSON string", ClientPayComponentResponse.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `payComponent`
      if (jsonObj.get("payComponent") != null && !jsonObj.get("payComponent").isJsonNull()) {
        PayComponent.validateJsonObject(jsonObj.getAsJsonObject("payComponent"));
      }
      // validate the optional field `frequencyData`
      if (jsonObj.get("frequencyData") != null && !jsonObj.get("frequencyData").isJsonNull()) {
        ClientPayComponentFrequency.validateJsonObject(jsonObj.getAsJsonObject("frequencyData"));
      }
      if (jsonObj.get("calcMethods") != null && !jsonObj.get("calcMethods").isJsonNull()) {
        JsonArray jsonArraycalcMethods = jsonObj.getAsJsonArray("calcMethods");
        if (jsonArraycalcMethods != null) {
          // ensure the json data is an array
          if (!jsonObj.get("calcMethods").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `calcMethods` to be an array in the JSON string but got `%s`", jsonObj.get("calcMethods").toString()));
          }

          // validate the optional field `calcMethods` (array)
          for (int i = 0; i < jsonArraycalcMethods.size(); i++) {
            CalcMethod.validateJsonObject(jsonArraycalcMethods.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("workerTypes") != null && !jsonObj.get("workerTypes").isJsonNull()) {
        JsonArray jsonArrayworkerTypes = jsonObj.getAsJsonArray("workerTypes");
        if (jsonArrayworkerTypes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("workerTypes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `workerTypes` to be an array in the JSON string but got `%s`", jsonObj.get("workerTypes").toString()));
          }

          // validate the optional field `workerTypes` (array)
          for (int i = 0; i < jsonArrayworkerTypes.size(); i++) {
            ClientPayComponentWorkerTypes.validateJsonObject(jsonArrayworkerTypes.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("options") != null && !jsonObj.get("options").isJsonNull()) {
        JsonArray jsonArrayoptions = jsonObj.getAsJsonArray("options");
        if (jsonArrayoptions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("options").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `options` to be an array in the JSON string but got `%s`", jsonObj.get("options").toString()));
          }

          // validate the optional field `options` (array)
          for (int i = 0; i < jsonArrayoptions.size(); i++) {
            ClientPayComponentOptions.validateJsonObject(jsonArrayoptions.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ClientPayComponentResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ClientPayComponentResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ClientPayComponentResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ClientPayComponentResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ClientPayComponentResponse>() {
           @Override
           public void write(JsonWriter out, ClientPayComponentResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ClientPayComponentResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ClientPayComponentResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ClientPayComponentResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ClientPayComponentResponse
  * @throws IOException if the JSON string is invalid with respect to ClientPayComponentResponse
  */
  public static ClientPayComponentResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ClientPayComponentResponse.class);
  }

 /**
  * Convert an instance of ClientPayComponentResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

