/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The workers legal tax identification information. This data field cannot be PATCHED for ACTIVE workers.
 */
@ApiModel(description = "The workers legal tax identification information. This data field cannot be PATCHED for ACTIVE workers.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class LegalIdResource1 {
  /**
   * A value that identifies the type of taxpayer identification number provided.   SSN: Social  Security Number - 9 digit number   , FEIN: Federal Employer Identification Number (EIN)
   */
  @JsonAdapter(LegalIdTypeEnum.Adapter.class)
 public enum LegalIdTypeEnum {
    SSN("SSN"),
    
    FEIN("FEIN");

    private String value;

    LegalIdTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LegalIdTypeEnum fromValue(String value) {
      for (LegalIdTypeEnum b : LegalIdTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LegalIdTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LegalIdTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LegalIdTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LegalIdTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_LEGAL_ID_TYPE = "legalIdType";
  @SerializedName(SERIALIZED_NAME_LEGAL_ID_TYPE)
  private LegalIdTypeEnum legalIdType;

  public static final String SERIALIZED_NAME_LEGAL_ID_VALUE = "legalIdValue";
  @SerializedName(SERIALIZED_NAME_LEGAL_ID_VALUE)
  private String legalIdValue;

  public LegalIdResource1() {
  }

  public LegalIdResource1 legalIdType(LegalIdTypeEnum legalIdType) {
    
    
    
    
    this.legalIdType = legalIdType;
    return this;
  }

   /**
   * A value that identifies the type of taxpayer identification number provided.   SSN: Social  Security Number - 9 digit number   , FEIN: Federal Employer Identification Number (EIN)
   * @return legalIdType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A value that identifies the type of taxpayer identification number provided.   SSN: Social  Security Number - 9 digit number   , FEIN: Federal Employer Identification Number (EIN)")

  public LegalIdTypeEnum getLegalIdType() {
    return legalIdType;
  }


  public void setLegalIdType(LegalIdTypeEnum legalIdType) {
    
    
    
    this.legalIdType = legalIdType;
  }


  public LegalIdResource1 legalIdValue(String legalIdValue) {
    
    
    
    
    this.legalIdValue = legalIdValue;
    return this;
  }

   /**
   * The federal level taxpayer id number that the worker has provided
   * @return legalIdValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "333221111", value = "The federal level taxpayer id number that the worker has provided")

  public String getLegalIdValue() {
    return legalIdValue;
  }


  public void setLegalIdValue(String legalIdValue) {
    
    
    
    this.legalIdValue = legalIdValue;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the LegalIdResource1 instance itself
   */
  public LegalIdResource1 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegalIdResource1 legalIdResource1 = (LegalIdResource1) o;
    return Objects.equals(this.legalIdType, legalIdResource1.legalIdType) &&
        Objects.equals(this.legalIdValue, legalIdResource1.legalIdValue)&&
        Objects.equals(this.additionalProperties, legalIdResource1.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(legalIdType, legalIdValue, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegalIdResource1 {\n");
    sb.append("    legalIdType: ").append(toIndentedString(legalIdType)).append("\n");
    sb.append("    legalIdValue: ").append(toIndentedString(legalIdValue)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("legalIdType");
    openapiFields.add("legalIdValue");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LegalIdResource1
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LegalIdResource1.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LegalIdResource1 is not found in the empty JSON string", LegalIdResource1.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("legalIdType") != null && !jsonObj.get("legalIdType").isJsonNull()) && !jsonObj.get("legalIdType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `legalIdType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("legalIdType").toString()));
      }
      if ((jsonObj.get("legalIdValue") != null && !jsonObj.get("legalIdValue").isJsonNull()) && !jsonObj.get("legalIdValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `legalIdValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("legalIdValue").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LegalIdResource1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LegalIdResource1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LegalIdResource1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LegalIdResource1.class));

       return (TypeAdapter<T>) new TypeAdapter<LegalIdResource1>() {
           @Override
           public void write(JsonWriter out, LegalIdResource1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public LegalIdResource1 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             LegalIdResource1 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LegalIdResource1 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LegalIdResource1
  * @throws IOException if the JSON string is invalid with respect to LegalIdResource1
  */
  public static LegalIdResource1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LegalIdResource1.class);
  }

 /**
  * Convert an instance of LegalIdResource1 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

