/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FrequencyIntervalsResource1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Worker pay frequency
 */
@ApiModel(description = "Worker pay frequency")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PayComponentFrequencyTypeResource1 {
  public static final String SERIALIZED_NAME_APPLIED = "applied";
  @SerializedName(SERIALIZED_NAME_APPLIED)
  private String applied;

  public static final String SERIALIZED_NAME_OCCURRENCE = "occurrence";
  @SerializedName(SERIALIZED_NAME_OCCURRENCE)
  private String occurrence;

  public static final String SERIALIZED_NAME_OCCURRENCE_INTERVALS = "occurrenceIntervals";
  @SerializedName(SERIALIZED_NAME_OCCURRENCE_INTERVALS)
  private FrequencyIntervalsResource1 occurrenceIntervals;

  public static final String SERIALIZED_NAME_EFFECTED_CHECKS = "effectedChecks";
  @SerializedName(SERIALIZED_NAME_EFFECTED_CHECKS)
  private String effectedChecks;

  public PayComponentFrequencyTypeResource1() {
  }

  public PayComponentFrequencyTypeResource1 applied(String applied) {
    
    
    
    
    this.applied = applied;
    return this;
  }

   /**
   * Currently we only support a BY_PAY_PERIOD value for the API.
   * @return applied
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "BY_PAY_PERIOD", value = "Currently we only support a BY_PAY_PERIOD value for the API.")

  public String getApplied() {
    return applied;
  }


  public void setApplied(String applied) {
    
    
    
    this.applied = applied;
  }


  public PayComponentFrequencyTypeResource1 occurrence(String occurrence) {
    
    
    
    
    this.occurrence = occurrence;
    return this;
  }

   /**
   * This is how often the pay component will be applied on the pay run. The available values for this will depend on the payFrequency that a worker is paid which can be found on the worker compensations pay standards.
   * @return occurrence
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "QUARTERLY", value = "This is how often the pay component will be applied on the pay run. The available values for this will depend on the payFrequency that a worker is paid which can be found on the worker compensations pay standards.")

  public String getOccurrence() {
    return occurrence;
  }


  public void setOccurrence(String occurrence) {
    
    
    
    this.occurrence = occurrence;
  }


  public PayComponentFrequencyTypeResource1 occurrenceIntervals(FrequencyIntervalsResource1 occurrenceIntervals) {
    
    
    
    
    this.occurrenceIntervals = occurrenceIntervals;
    return this;
  }

   /**
   * Get occurrenceIntervals
   * @return occurrenceIntervals
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FrequencyIntervalsResource1 getOccurrenceIntervals() {
    return occurrenceIntervals;
  }


  public void setOccurrenceIntervals(FrequencyIntervalsResource1 occurrenceIntervals) {
    
    
    
    this.occurrenceIntervals = occurrenceIntervals;
  }


  public PayComponentFrequencyTypeResource1 effectedChecks(String effectedChecks) {
    
    
    
    
    this.effectedChecks = effectedChecks;
    return this;
  }

   /**
   * Which check(s) within the payrun that the paycomponent will be applied to.FIRST_CHECK: The Pay Component will be applied to the first check for the worker within the pay run. This is used for a pay component that only should be applied once like a health insurance deduction.EVERY_CHECK: The Pay Component will be applied to all of the checks for the worker within the pay run. This is used for a pay component that is applied on all check like a retirement deduction.
   * @return effectedChecks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "EVERY_CHECK", value = "Which check(s) within the payrun that the paycomponent will be applied to.FIRST_CHECK: The Pay Component will be applied to the first check for the worker within the pay run. This is used for a pay component that only should be applied once like a health insurance deduction.EVERY_CHECK: The Pay Component will be applied to all of the checks for the worker within the pay run. This is used for a pay component that is applied on all check like a retirement deduction.")

  public String getEffectedChecks() {
    return effectedChecks;
  }


  public void setEffectedChecks(String effectedChecks) {
    
    
    
    this.effectedChecks = effectedChecks;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PayComponentFrequencyTypeResource1 instance itself
   */
  public PayComponentFrequencyTypeResource1 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayComponentFrequencyTypeResource1 payComponentFrequencyTypeResource1 = (PayComponentFrequencyTypeResource1) o;
    return Objects.equals(this.applied, payComponentFrequencyTypeResource1.applied) &&
        Objects.equals(this.occurrence, payComponentFrequencyTypeResource1.occurrence) &&
        Objects.equals(this.occurrenceIntervals, payComponentFrequencyTypeResource1.occurrenceIntervals) &&
        Objects.equals(this.effectedChecks, payComponentFrequencyTypeResource1.effectedChecks)&&
        Objects.equals(this.additionalProperties, payComponentFrequencyTypeResource1.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applied, occurrence, occurrenceIntervals, effectedChecks, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayComponentFrequencyTypeResource1 {\n");
    sb.append("    applied: ").append(toIndentedString(applied)).append("\n");
    sb.append("    occurrence: ").append(toIndentedString(occurrence)).append("\n");
    sb.append("    occurrenceIntervals: ").append(toIndentedString(occurrenceIntervals)).append("\n");
    sb.append("    effectedChecks: ").append(toIndentedString(effectedChecks)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("applied");
    openapiFields.add("occurrence");
    openapiFields.add("occurrenceIntervals");
    openapiFields.add("effectedChecks");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PayComponentFrequencyTypeResource1
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PayComponentFrequencyTypeResource1.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PayComponentFrequencyTypeResource1 is not found in the empty JSON string", PayComponentFrequencyTypeResource1.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("applied") != null && !jsonObj.get("applied").isJsonNull()) && !jsonObj.get("applied").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `applied` to be a primitive type in the JSON string but got `%s`", jsonObj.get("applied").toString()));
      }
      if ((jsonObj.get("occurrence") != null && !jsonObj.get("occurrence").isJsonNull()) && !jsonObj.get("occurrence").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `occurrence` to be a primitive type in the JSON string but got `%s`", jsonObj.get("occurrence").toString()));
      }
      // validate the optional field `occurrenceIntervals`
      if (jsonObj.get("occurrenceIntervals") != null && !jsonObj.get("occurrenceIntervals").isJsonNull()) {
        FrequencyIntervalsResource1.validateJsonObject(jsonObj.getAsJsonObject("occurrenceIntervals"));
      }
      if ((jsonObj.get("effectedChecks") != null && !jsonObj.get("effectedChecks").isJsonNull()) && !jsonObj.get("effectedChecks").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `effectedChecks` to be a primitive type in the JSON string but got `%s`", jsonObj.get("effectedChecks").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PayComponentFrequencyTypeResource1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PayComponentFrequencyTypeResource1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PayComponentFrequencyTypeResource1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PayComponentFrequencyTypeResource1.class));

       return (TypeAdapter<T>) new TypeAdapter<PayComponentFrequencyTypeResource1>() {
           @Override
           public void write(JsonWriter out, PayComponentFrequencyTypeResource1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PayComponentFrequencyTypeResource1 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PayComponentFrequencyTypeResource1 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PayComponentFrequencyTypeResource1 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PayComponentFrequencyTypeResource1
  * @throws IOException if the JSON string is invalid with respect to PayComponentFrequencyTypeResource1
  */
  public static PayComponentFrequencyTypeResource1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PayComponentFrequencyTypeResource1.class);
  }

 /**
  * Convert an instance of PayComponentFrequencyTypeResource1 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

