/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The postal communications for this contact.
 */
@ApiModel(description = "The postal communications for this contact.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PostalResource {
  public static final String SERIALIZED_NAME_COMMUNICATION_ID = "communicationId";
  @SerializedName(SERIALIZED_NAME_COMMUNICATION_ID)
  private String communicationId;

  public static final String SERIALIZED_NAME_STREET_LINE_ONE = "streetLineOne";
  @SerializedName(SERIALIZED_NAME_STREET_LINE_ONE)
  private String streetLineOne;

  public static final String SERIALIZED_NAME_STREET_LINE_TWO = "streetLineTwo";
  @SerializedName(SERIALIZED_NAME_STREET_LINE_TWO)
  private String streetLineTwo;

  public static final String SERIALIZED_NAME_POST_OFFICE_BOX = "postOfficeBox";
  @SerializedName(SERIALIZED_NAME_POST_OFFICE_BOX)
  private String postOfficeBox;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  private String postalCode;

  public static final String SERIALIZED_NAME_COUNTRY_SUBDIVISION_CODE = "countrySubdivisionCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_SUBDIVISION_CODE)
  private String countrySubdivisionCode;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "countryCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  private String countryCode;

  public PostalResource() {
  }

  public PostalResource communicationId(String communicationId) {
    
    
    
    
    this.communicationId = communicationId;
    return this;
  }

   /**
   * The ID for the workers relationship to contact.
   * @return communicationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID for the workers relationship to contact.")

  public String getCommunicationId() {
    return communicationId;
  }


  public void setCommunicationId(String communicationId) {
    
    
    
    this.communicationId = communicationId;
  }


  public PostalResource streetLineOne(String streetLineOne) {
    
    
    
    
    this.streetLineOne = streetLineOne;
    return this;
  }

   /**
   * The street address line one. Required for street address. Required for POST contacts.
   * @return streetLineOne
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The street address line one. Required for street address. Required for POST contacts.")

  public String getStreetLineOne() {
    return streetLineOne;
  }


  public void setStreetLineOne(String streetLineOne) {
    
    
    
    this.streetLineOne = streetLineOne;
  }


  public PostalResource streetLineTwo(String streetLineTwo) {
    
    
    
    
    this.streetLineTwo = streetLineTwo;
    return this;
  }

   /**
   * The street address line two.
   * @return streetLineTwo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The street address line two.")

  public String getStreetLineTwo() {
    return streetLineTwo;
  }


  public void setStreetLineTwo(String streetLineTwo) {
    
    
    
    this.streetLineTwo = streetLineTwo;
  }


  public PostalResource postOfficeBox(String postOfficeBox) {
    
    
    
    
    this.postOfficeBox = postOfficeBox;
    return this;
  }

   /**
   * The postal office box. Required for PO Box with POST contacts.
   * @return postOfficeBox
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The postal office box. Required for PO Box with POST contacts.")

  public String getPostOfficeBox() {
    return postOfficeBox;
  }


  public void setPostOfficeBox(String postOfficeBox) {
    
    
    
    this.postOfficeBox = postOfficeBox;
  }


  public PostalResource city(String city) {
    
    
    
    
    this.city = city;
    return this;
  }

   /**
   * The city name. Required for POST contacts.
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The city name. Required for POST contacts.")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    
    
    
    this.city = city;
  }


  public PostalResource postalCode(String postalCode) {
    
    
    
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The zip-code. Required for POST contacts.
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The zip-code. Required for POST contacts.")

  public String getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(String postalCode) {
    
    
    
    this.postalCode = postalCode;
  }


  public PostalResource countrySubdivisionCode(String countrySubdivisionCode) {
    
    
    
    
    this.countrySubdivisionCode = countrySubdivisionCode;
    return this;
  }

   /**
   * The state code (ISO 3166 subdivision code). Required for POST contacts.
   * @return countrySubdivisionCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The state code (ISO 3166 subdivision code). Required for POST contacts.")

  public String getCountrySubdivisionCode() {
    return countrySubdivisionCode;
  }


  public void setCountrySubdivisionCode(String countrySubdivisionCode) {
    
    
    
    this.countrySubdivisionCode = countrySubdivisionCode;
  }


  public PostalResource countryCode(String countryCode) {
    
    
    
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * The country code (ISO 3166 alpha-2). Required for POST contacts.
   * @return countryCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The country code (ISO 3166 alpha-2). Required for POST contacts.")

  public String getCountryCode() {
    return countryCode;
  }


  public void setCountryCode(String countryCode) {
    
    
    
    this.countryCode = countryCode;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PostalResource instance itself
   */
  public PostalResource putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostalResource postalResource = (PostalResource) o;
    return Objects.equals(this.communicationId, postalResource.communicationId) &&
        Objects.equals(this.streetLineOne, postalResource.streetLineOne) &&
        Objects.equals(this.streetLineTwo, postalResource.streetLineTwo) &&
        Objects.equals(this.postOfficeBox, postalResource.postOfficeBox) &&
        Objects.equals(this.city, postalResource.city) &&
        Objects.equals(this.postalCode, postalResource.postalCode) &&
        Objects.equals(this.countrySubdivisionCode, postalResource.countrySubdivisionCode) &&
        Objects.equals(this.countryCode, postalResource.countryCode)&&
        Objects.equals(this.additionalProperties, postalResource.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(communicationId, streetLineOne, streetLineTwo, postOfficeBox, city, postalCode, countrySubdivisionCode, countryCode, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostalResource {\n");
    sb.append("    communicationId: ").append(toIndentedString(communicationId)).append("\n");
    sb.append("    streetLineOne: ").append(toIndentedString(streetLineOne)).append("\n");
    sb.append("    streetLineTwo: ").append(toIndentedString(streetLineTwo)).append("\n");
    sb.append("    postOfficeBox: ").append(toIndentedString(postOfficeBox)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    countrySubdivisionCode: ").append(toIndentedString(countrySubdivisionCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("communicationId");
    openapiFields.add("streetLineOne");
    openapiFields.add("streetLineTwo");
    openapiFields.add("postOfficeBox");
    openapiFields.add("city");
    openapiFields.add("postalCode");
    openapiFields.add("countrySubdivisionCode");
    openapiFields.add("countryCode");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PostalResource
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PostalResource.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostalResource is not found in the empty JSON string", PostalResource.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("communicationId") != null && !jsonObj.get("communicationId").isJsonNull()) && !jsonObj.get("communicationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `communicationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("communicationId").toString()));
      }
      if ((jsonObj.get("streetLineOne") != null && !jsonObj.get("streetLineOne").isJsonNull()) && !jsonObj.get("streetLineOne").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `streetLineOne` to be a primitive type in the JSON string but got `%s`", jsonObj.get("streetLineOne").toString()));
      }
      if ((jsonObj.get("streetLineTwo") != null && !jsonObj.get("streetLineTwo").isJsonNull()) && !jsonObj.get("streetLineTwo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `streetLineTwo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("streetLineTwo").toString()));
      }
      if ((jsonObj.get("postOfficeBox") != null && !jsonObj.get("postOfficeBox").isJsonNull()) && !jsonObj.get("postOfficeBox").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `postOfficeBox` to be a primitive type in the JSON string but got `%s`", jsonObj.get("postOfficeBox").toString()));
      }
      if ((jsonObj.get("city") != null && !jsonObj.get("city").isJsonNull()) && !jsonObj.get("city").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `city` to be a primitive type in the JSON string but got `%s`", jsonObj.get("city").toString()));
      }
      if ((jsonObj.get("postalCode") != null && !jsonObj.get("postalCode").isJsonNull()) && !jsonObj.get("postalCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `postalCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("postalCode").toString()));
      }
      if ((jsonObj.get("countrySubdivisionCode") != null && !jsonObj.get("countrySubdivisionCode").isJsonNull()) && !jsonObj.get("countrySubdivisionCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `countrySubdivisionCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countrySubdivisionCode").toString()));
      }
      if ((jsonObj.get("countryCode") != null && !jsonObj.get("countryCode").isJsonNull()) && !jsonObj.get("countryCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `countryCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countryCode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostalResource.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostalResource' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostalResource> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostalResource.class));

       return (TypeAdapter<T>) new TypeAdapter<PostalResource>() {
           @Override
           public void write(JsonWriter out, PostalResource value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PostalResource read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PostalResource instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PostalResource given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PostalResource
  * @throws IOException if the JSON string is invalid with respect to PostalResource
  */
  public static PostalResource fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostalResource.class);
  }

 /**
  * Convert an instance of PostalResource to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

