/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The relationship type for this worker contact. Required for POST person contacts.
 */
@ApiModel(description = "The relationship type for this worker contact. Required for POST person contacts.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class RelationTypeResource1 {
  public static final String SERIALIZED_NAME_RELATIONSHIP_TYPE_ID = "relationshipTypeId";
  @SerializedName(SERIALIZED_NAME_RELATIONSHIP_TYPE_ID)
  private String relationshipTypeId;

  public static final String SERIALIZED_NAME_RELATIONSHIP_TYPE_NAME = "relationshipTypeName";
  @SerializedName(SERIALIZED_NAME_RELATIONSHIP_TYPE_NAME)
  private String relationshipTypeName;

  public RelationTypeResource1() {
  }

  public RelationTypeResource1 relationshipTypeId(String relationshipTypeId) {
    
    
    
    
    this.relationshipTypeId = relationshipTypeId;
    return this;
  }

   /**
   * ID of worker specific type of relationship with the contact. Required for POST contacts.
   * @return relationshipTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ID of worker specific type of relationship with the contact. Required for POST contacts.")

  public String getRelationshipTypeId() {
    return relationshipTypeId;
  }


  public void setRelationshipTypeId(String relationshipTypeId) {
    
    
    
    this.relationshipTypeId = relationshipTypeId;
  }


  public RelationTypeResource1 relationshipTypeName(String relationshipTypeName) {
    
    
    
    
    this.relationshipTypeName = relationshipTypeName;
    return this;
  }

   /**
   * The name of worker specific type of relationship with the contact.  Enum: \&quot;Spouse\&quot;, \&quot;Parent\&quot;, \&quot;Sibling\&quot;, \&quot;Child\&quot;,  \&quot;Friend\&quot;, \&quot;Domestic Partner\&quot;, \&quot;Other\&quot;
   * @return relationshipTypeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of worker specific type of relationship with the contact.  Enum: \"Spouse\", \"Parent\", \"Sibling\", \"Child\",  \"Friend\", \"Domestic Partner\", \"Other\"")

  public String getRelationshipTypeName() {
    return relationshipTypeName;
  }


  public void setRelationshipTypeName(String relationshipTypeName) {
    
    
    
    this.relationshipTypeName = relationshipTypeName;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RelationTypeResource1 instance itself
   */
  public RelationTypeResource1 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelationTypeResource1 relationTypeResource1 = (RelationTypeResource1) o;
    return Objects.equals(this.relationshipTypeId, relationTypeResource1.relationshipTypeId) &&
        Objects.equals(this.relationshipTypeName, relationTypeResource1.relationshipTypeName)&&
        Objects.equals(this.additionalProperties, relationTypeResource1.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relationshipTypeId, relationshipTypeName, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelationTypeResource1 {\n");
    sb.append("    relationshipTypeId: ").append(toIndentedString(relationshipTypeId)).append("\n");
    sb.append("    relationshipTypeName: ").append(toIndentedString(relationshipTypeName)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("relationshipTypeId");
    openapiFields.add("relationshipTypeName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RelationTypeResource1
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RelationTypeResource1.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RelationTypeResource1 is not found in the empty JSON string", RelationTypeResource1.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("relationshipTypeId") != null && !jsonObj.get("relationshipTypeId").isJsonNull()) && !jsonObj.get("relationshipTypeId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `relationshipTypeId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relationshipTypeId").toString()));
      }
      if ((jsonObj.get("relationshipTypeName") != null && !jsonObj.get("relationshipTypeName").isJsonNull()) && !jsonObj.get("relationshipTypeName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `relationshipTypeName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relationshipTypeName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RelationTypeResource1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RelationTypeResource1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RelationTypeResource1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RelationTypeResource1.class));

       return (TypeAdapter<T>) new TypeAdapter<RelationTypeResource1>() {
           @Override
           public void write(JsonWriter out, RelationTypeResource1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RelationTypeResource1 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             RelationTypeResource1 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RelationTypeResource1 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RelationTypeResource1
  * @throws IOException if the JSON string is invalid with respect to RelationTypeResource1
  */
  public static RelationTypeResource1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RelationTypeResource1.class);
  }

 /**
  * Convert an instance of RelationTypeResource1 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

