/*
 * External API
 *   # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Authentication;
import com.konfigthis.client.model.AuthenticationCreateBearerTokenRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
@Disabled
public class AuthenticationApiTest {

    private static AuthenticationApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AuthenticationApi(apiClient);
    }

    /**
     * Create Bearer token
     *
     * Request a Bearer token that will be used as an access token when making calls to resources.  The credentials need to be sent within the body of the request.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createBearerTokenTest() throws ApiException {
        String grantType = null;
        String clientId = null;
        String clientSecret = null;
        Authentication response = api.createBearerToken(grantType, clientId, clientSecret)
                .execute();
        // TODO: test validations
    }

}
